name: CI

on:
  pull_request:
    branches: [main]
    # only run when firmware or workflow files change (you can broaden later)
    paths:
      - "firmware/**"
      - ".github/workflows/**"

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            .pio
          key: pio-${{ runner.os }}-${{ hashFiles('firmware/platformio.ini') }}
          restore-keys: |
            pio-${{ runner.os }}-

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build (all envs)
        working-directory: firmware
        run: pio run
